version: '3.8'

services:
  frontend-crisisview:
    image: rainder/frontend-crisisview:latest
    container_name: frontend_app
    restart: always
    ports:
      - "3001:3000"
    networks:
      - devops2
    
    environment:
      - NODE_ENV=production

networks:
  devops2:
    external: true
